### ISSUE TITLE
Hoàn thành PRODUCT FEATURES và OPERATING ENVIRONMENT

### ISSUE THREAD

**Issue by fevirtus** [fevirtus/PA#1]
Nghiên cứu và hoàn thành 2 mục PRODUCT FEATURES và OPERATING ENVIRONMENT trong SRS.
Mô tả: 
+ PRODUCT FEATURES: Sử dụng class diagram để mô tả được các đối tượng và mối quan hệ giữa các class.
+ OPERATING ENVIRONMENT: Mô tả rõ công nghệ, ngông ngữ và OS hệ thống sử dụng

**Comment by fogr** [comment]
Diagram added
